language: cpp
sudo: required
dist: trusty

branches:
  only:
    - master

osx_image: xcode8
os:
  - linux
  - osx

env:
  - CONFIG=Release
  - CONFIG=Debug

compiler:
  - clang
  - gcc

before_install:
  - QT_VERSION_MM=57
  - QT_VERSION_FULL=571-trusty
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository ppa:beineri/opt-qt$QT_VERSION_FULL -y
      && sudo apt-get update -qq
      && sudo apt-get install -y

      qt${QT_VERSION_MM}base qt${QT_VERSION_MM}tools
      && export CMAKE_PREFIX_PATH=/opt/qt${QT_VERSION_MM};
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update;
      brew outdated cmake || brew upgrade cmake;
      brew install qt5;
      export CMAKE_PREFIX_PATH=$(brew --prefix qt5);
    fi



before_script:
   - mkdir build
   - cd build
   - cmake ../src/


script:
   - cmake --build . --config $CONFIG &&
     ctest --output-on-failure
