sudo: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: require
      addons:
        apt:
          sources:
             - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode9.2
      compiler: clang
      env:
        - MATRIX_EVAL="COMPILER=clang++"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - QT_VERSION=qt511
  - QT_VERSION_FULL=qt-5.11.1
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo add-apt-repository --yes ppa:beineri/opt-${QT_VERSION_FULL}-trusty;
      sudo apt update -qq;
      sudo apt search ${QT_VERSION};
      sudo apt install build-essential ${QT_VERSION}-meta-minimal/trusty ${QT_VERSION}quickcontrols/trusty ${QT_VERSION}quickcontrols2/trusty ${QT_VERSION}graphicaleffects/trusty ${QT_VERSION}svg/trusty ${QT_VERSION}scxml/trusty git;
      fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update > /dev/null;
      brew install qt5;
      chmod -R 755 /usr/local/opt/qt5/*;
      export QTDIR="/usr/local/opt/qt5";
      export PATH="$QTDIR/bin:$PATH";
      fi

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      source /opt/qt*/bin/qt*-env.sh;
      mkdir build;
      cd build;
      cmake ../src/;
      make;
      fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      mkdir build;
      cd build;
      cmake ../src/;
      make;
      fi